[package]
name = "laggame"
version = "0.1.0"
authors = ["Mason Kramer <mason@masonkramer.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.2.1"
bevy_rapier2d = "0.3.1"
